HuoChong.Web/ViewComponents/GlobalSearchViewComponent.cs
using HuoChong.Data.IRepository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HuoChong.Web.ViewComponents
{
    public class GlobalSearchViewComponent : ViewComponent
    {
        public readonly IColumnRepository _columnRepository;
        public GlobalSearchViewComponent(IColumnRepository columnRepository)
        {
            _columnRepository = columnRepository;
        }
        public async Task<IViewComponentResult> InvokeAsync(int cinemaId)
        {
            return View(await _columnRepository.GetListAsync("where parentid=0"));
            
        }
    }
}

HuoChong.Web/ViewComponents/NavViewComponent.cs
using HuoChong.Data.IRepository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HuoChong.WebManage.ViewComponents
{
    public class NavViewComponent : ViewComponent
    {
        public readonly IColumnRepository _columnRepository;
        public NavViewComponent(IColumnRepository columnRepository)
        {
            _columnRepository = columnRepository;
        }
        public async Task<IViewComponentResult> InvokeAsync(int cinemaId)
        {
         ViewData["AllColumn"]=   await _columnRepository.GetListAsync();
            return View();
        }
    }
}

HuoChong.Web/Views/Shared/_GlobalLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>@ViewData["Title"]</title>
    <meta name="keywords" content="@ViewData["keywords"]" />
    <meta name="description" content="@ViewData["Description"]" />
    <environment exclude="Development">
        <link href="~/css/base.min.css" rel="stylesheet" asp-append-version="true"/>
        <link href="~/css/m.css" rel="stylesheet" asp-append-version="true"/>
        <script src="/js/jquery-1.8.3.min.js"></script>
    </environment>
    <environment include="Development">      
        <link href="~/css/base.css" rel="stylesheet" asp-append-version="true" />
        <link href="/css/m.css" rel="stylesheet" asp-append-version="true" />
        <script src="/js/jquery-1.8.3.min.js"></script>
    </environment>
    @RenderSection("css", false)
    @RenderSection("js", false)
</head>
<body>
    <header id="header">
        <div class="navbox">
            <h2 id="mnavh"><span class="navicon"></span></h2>
            <div class="logo"><a href="/" title="火虫网"><img src="~/image/logo.png" alt="火虫网" /></a></div>
            @await Component.InvokeAsync("Nav")
            <div class="searchico"></div>
        </div>
    </header>
    @await Component.InvokeAsync("GlobalSearch")
    <article>
        @RenderBody()
    </article>
    <footer>
        <div class="box">
            <div class="wxbox">
                <ul>
                    <li><img src="/image/wxhuochong.jpg"><span>微信公众号</span></li>
                    <li><img src="/image/mywx.jpg"><span>我的微信</span></li>
                </ul>
            </div>
            <div class="endnav">
                <p><b>站点声明：</b></p>
                <p>Copyright © 2018 52huochong.com All rights reserved.<a href="http://www.miitbeian.gov.cn/" target="_blank"> 浙ICP备19000582号</a></p>
                <p>
                    <a target="_blank" href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=33010602009921" style="display:inline-block;text-decoration:none;height:20px;line-height:20px;">
                        <img src="/image/beian.png" style="float:left;" />
                        浙公网安备 33010602009921号
                    </a>
                </p>
            </div>
        </div>
        <a href="#">
            <div class="top"></div>
        </a>
    </footer>
    <script>
        (function () {
            var bp = document.createElement('script');
            var curProtocol = window.location.protocol.split(':')[0];
            if (curProtocol === 'https') {
                bp.src = 'https://zz.bdstatic.com/linksubmit/push.js';
            }
            else {
                bp.src = 'http://push.zhanzhang.baidu.com/push.js';
            }
            var s = document.getElementsByTagName("script")[0];
            s.parentNode.insertBefore(bp, s);
        })();
        var _hmt = _hmt || [];
        (function () {
            var hm = document.createElement("script");
            hm.src = "https://hm.baidu.com/hm.js?ee40cb7a7b9893f41b9c164497e7cea9";
            var s = document.getElementsByTagName("script")[0];
            s.parentNode.insertBefore(hm, s);
        })();
    </script>
    <script src="~/js/echo.min.js"></script>
    <script src="~/js/nav.min.js" asp-append-version="true"></script>
    <script src="/js/comm.js" asp-append-version="true"></script>  
</body>
</html>

HuoChong.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>@ViewData["Title"]</title>
    <meta name="keywords" content="@ViewData["keywords"]" />
    <meta name="description" content="@ViewData["Description"]" />
    <environment exclude="Development">
        <link href="~/css/index.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/base.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/m.min.css" rel="stylesheet" asp-append-version="true" />
    </environment>
    <environment include="Development">
        <link href="~/css/index.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/base.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/m.min.css" rel="stylesheet" asp-append-version="true" />
    </environment>
    <script src="~/js/jquery-2.1.1.min.js"></script>
    @RenderSection("css", false)
    @RenderSection("js", false)
</head>
<body>
    <header id="header">
        <div id="mnav">
            <div class="logo"><a href="/" title="火虫网"><img src="~/image/logo.png" alt="火虫网" /></a></div>
            <h2 id="mnavh"><span class="navicon"></span></h2>
            @await Component.InvokeAsync("Nav")
        </div>
        <script>
            window.onload = function () {
                var oH2 = document.getElementById("mnavh");
                var oUl = document.getElementById("starlist");
                oH2.onclick = function () {
                    var style = oUl.style;
                    style.display = style.display == "block" ? "none" : "block";
                    oH2.className = style.display == "block" ? "open" : ""
                }
            }
        </script>
    </header>
    <div class="line46"></div>
    <article>
        @RenderBody()
    </article>
    <footer>
        <div class="yqlj">
            <a href="@Url.Action("About","Home")" target="_self">关于火虫</a>
            <a href="@Url.Action("yijian","home")">意见反馈</a>
            <a class="qq" href="tencent://message/?uin=1248415209&Site=火虫网&Menu=yes">联系火虫</a>
        </div>
        <p> <a href="http://www.miitbeian.gov.cn/" target="_blank">浙ICP备19000582号</a>  Copyright © 2018 52huochong.com All rights reserved. 火虫网版权所有</p>

        <div style="width:300px;margin:0 auto; padding:20px 0;">

            <a target="_blank" href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=33010602009921" style="display:inline-block;text-decoration:none;height:20px;line-height:20px;">
                <img src="/images/beian.png" style="float:left;" />
                <p style="float:left;height:20px;line-height:20px;margin: 0px 0px 0px 5px; color:#939393;">浙公网安备 33010602009921号</p>
            </a>
        </div>
        <a href="#">
            <div class="top"></div>
        </a>
    </footer>
    <script>
        (function () {
            var bp = document.createElement('script');
            var curProtocol = window.location.protocol.split(':')[0];
            if (curProtocol === 'https') {
                bp.src = 'https://zz.bdstatic.com/linksubmit/push.js';
            }
            else {
                bp.src = 'http://push.zhanzhang.baidu.com/push.js';
            }
            var s = document.getElementsByTagName("script")[0];
            s.parentNode.insertBefore(bp, s);
        })();
        var _hmt = _hmt || [];
        (function () {
            var hm = document.createElement("script");
            hm.src = "https://hm.baidu.com/hm.js?ee40cb7a7b9893f41b9c164497e7cea9";
            var s = document.getElementsByTagName("script")[0];
            s.parentNode.insertBefore(hm, s);
        })();
    </script>
    <script src="~/js/echo.min.js"></script>
    <script src="~/js/nav.min.js" asp-append-version="true"></script>
</body>
</html>