HuoChong.Web/Controllers/HomeController.cs
using HuoChong.Data.IRepository;
using HuoChong.Entity;
using HuoChong.Entity.ViewModel;
using HuoChong.Tools;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using QRCoder;
using System;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using X.PagedList;

namespace HuoChong.Web.Controllers
{
    public class HomeController : Controller
    {
        public readonly IQRCode _iQRCode;
        public readonly INewsRepository _newsRepository;
        public readonly IBrowseNumRepository _browseNumRepository;
        public readonly ILikeRepository _likeRepository;
        public readonly IColumnRepository _columnRepository;
        public readonly IMessageRepository _messageRepository;
        public readonly ISpliderSiteRepository _spliderSiteRepository;
        private IMemoryCache _cache;
        public HomeController(INewsRepository newsRepository, IMessageRepository messageRepository, IMemoryCache cache,
        IBrowseNumRepository browseNumRepository, ILikeRepository likeRepository, IColumnRepository columnRepository, ISpliderSiteRepository spliderSiteRepository, IQRCode iQRCode)
        {
            ////IOptions 需要每次重新启动项目加载配置，IOptionsMonitor 每次更改配置都会重新加载，不需要重新启动项目。     
            _newsRepository = newsRepository;
            _browseNumRepository = browseNumRepository;
            _likeRepository = likeRepository;
            _columnRepository = columnRepository;
            _messageRepository = messageRepository;
            _cache = cache;
            _spliderSiteRepository = spliderSiteRepository;
            _iQRCode = iQRCode;
        }
        [Route("/")]
        [Route("/index.html")]
        public async Task<IActionResult> Index()
        {
            IndexDataVM model = new IndexDataVM()
            {
                RecNewsList = (await _newsRepository.LoadIndexRecNews(6)).ToList(),
                CategoryNewsList = (await _newsRepository.LoadCategoryNews()).ToList(),
                BrowserNewsList = (await _newsRepository.GetByBrowseNewsAsync("week")).ToList(),
                LikeNewsList = (await _newsRepository.GetByLikeNewsAsync("week")).ToList(),
                AllChildColumnList = _columnRepository.GetAllChildcolumn(),
                NewNewsList = _newsRepository.GetNewNewsByParentColumn(8, "IT资讯"),
                RamdomLikeList = _newsRepository.GetNewNewsByParentColumn(10, "资源分享")
            };
            if (model == null)
            {
                return NotFound();
            }
            //ViewData["gg"] = _redisSettings.AccessKey;
            return View(model);
        }
        [HttpGet]
        [Route("/{columnUrl}/{id}.html")]
        public async Task<IActionResult> Detail(int id, string columnUrl = null)
        {
            if (id == 0 || string.IsNullOrEmpty(columnUrl))
                return NotFound();
          
           var model=  await _cache.GetOrCreateAsync($"deail-{id}", async x => { return await _newsRepository.NewsDetailAsync(id); });
           
            if (!model.ColumnUrl.Equals(columnUrl))
            {
                return NotFound();
            }
            var upModel = await _newsRepository.LoadPreNextNews(id, model.ColumnUrl, "pre"); ViewBag.UpNews = upModel?.Title;
            ViewBag.UpId = upModel?.Id;

            var nextModel = await _newsRepository.LoadPreNextNews(id, model.ColumnUrl, "next");
            ViewBag.NextNews = nextModel?.Title;
            ViewBag.NextId = nextModel?.Id;
            ViewData["CurrentColumnUrl"] = columnUrl;
            if (model.ColumnId == 0)
            {
                throw new ArgumentNullException(nameof(model.ColumnId));
            }

            ViewData["NewsColumnRelated"] = await _newsRepository.LoadNewsColumnRelated(model.ColumnId, 6);
            await _browseNumRepository.InsertAsync(new BrowseNum
            {
                NewsId = id,
                IP = HttpContext.Request.Headers["X-Forwarded-For"].FirstOrDefault() ?? HttpContext.Connection.RemoteIpAddress.ToString()
            });
            return View(model);
        }
        [HttpPost]
        public async Task<string> ClickLikeNews(int newsId)
        {
            bool i = await _likeRepository.InsertAsync(new Like()
            {
                NewsId = newsId,
                IP = HttpContext.Request.Headers["X-Forwarded-For"].FirstOrDefault() ?? HttpContext.Connection.RemoteIpAddress.ToString(),
                CreateTime = DateTime.Now
            });
            return i ? "ok" : "no";
        }
        [HttpGet]
        [Route("/cate/{columnParentSpell}/page-{page:int}.html")]
        [Route("/cate/{columnParentSpell}/")]
        public async Task<IActionResult> NewsList(string columnParentSpell, int page = 1)
        {
            if (string.IsNullOrEmpty(columnParentSpell))
                return NotFound();
            var allColumn = await _columnRepository.GetListAsync();
           
            var columnParentModel = allColumn.Where(a => a.Spell == columnParentSpell.Trim()).FirstOrDefault();
            if (columnParentModel == null)
            {
                return NotFound();
            }
            NewsListVM model = new NewsListVM()
            {
                CurrentColumnParentSpell = columnParentSpell,
                CurrentColumnParentName = columnParentModel.Name,
                Title = columnParentModel.Title,
                Keywords = columnParentModel.Keywords,
                Description = columnParentModel.Description,
                CurrentPageIndex = page,
                ChildColumnList = allColumn.Where(a => a.ParentId == columnParentModel.Id).ToList()
            };
            var query = await _newsRepository.LoadNewsPage(page, 15, columnParentSpell);
            if (query.Item1.Count < 0)
            {
                throw new ArgumentNullException(nameof(query.Item1));
            }
            ViewData["NewsList"] = query.Item1;
            ViewData["Page"] = new StaticPagedList<NewsPageVM>(query.Item1, page, 15, query.Item2);
            return View(model);
        }
        [HttpGet]
        public IActionResult LoadMessage(int newsId)
        {
            var query = _messageRepository.GetMessageList(newsId);
            if (query.Count > 0)
            {
                NLogHelp.InfoLog($"{DateTime.Now}{query.Count}");
            }
            return Json(new { data = query, count = query.Count });
        }
        [HttpPost]
        public string AddMessage(int newsId, string email, string content)
        {
            try
            {
                Message model = new Message();
                if (!string.IsNullOrEmpty(content) && !string.IsNullOrEmpty(email))
                {
                    model.NewsId = newsId;
                    model.Content = content;
                    model.Email = email;
                    model.IP = HttpContext.Request.Headers["X-Forwarded-For"].FirstOrDefault() ?? HttpContext.Connection.RemoteIpAddress.ToString();
                    model.Address = WebHelper.GetAddressByIP(model?.IP);
                    model.CreateTime = DateTime.Now;
                }
                return _messageRepository.Insert(model) == true ? "ok" : "no";
            }
            catch (Exception ex)
            {

                throw ex;
            }

        }
        //[Route("/search/{keyword}")]
        public async Task< IActionResult> Search(int page=1,string keyword=null)
        {
            if (string.IsNullOrEmpty(keyword))
            {
                return NotFound();
            }
           var data=await _newsRepository.LoadNewsPage(page, 24, keyword, 1, null, null, null,true);
            ViewData["NewsSearchList"] = data.Item1;
            TempData["CurrentKeyword"] = keyword;
            ViewData["Page"] = new StaticPagedList<NewsPageVM>(data.Item1, page, 24, data.Item2);
            return View();
        }
        [Route("/about.html")]
        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }
        [Route("/link.html")]
        public IActionResult Link()
        {
          var linkUrlList=  _spliderSiteRepository.GetList("where Type=1").ToList();
            ViewData["linkUrlList"] = linkUrlList;
            return View();
        }
        [Route("/cate/time")]
        public IActionResult Time()
        {
            return View();
        }

        [Route("/error/404")]
        public IActionResult Error()
        {
            return View();
        }
        /// <summary>
        /// 获取二维码
        /// </summary>
        /// <param name="url">存储内容</param>
        /// <param name="pixel">像素大小</param>
        /// <returns></returns>
        [HttpGet("/api/qrcode")]
        public void GetQRCode(string url, int pixel)
        {
            Response.ContentType = "image/jpeg";
            var bitmap = _iQRCode.GetQRCode(url, pixel);
            MemoryStream ms = new MemoryStream();
            bitmap.Save(ms, ImageFormat.Jpeg);

            Response.Body.WriteAsync(ms.GetBuffer(), 0, Convert.ToInt32(ms.Length));
            Response.Body.Close();
        }
        [Route("Barcode.aspx")]
        public IActionResult BarCode()
        {
            return View();
        }
    }
}

HuoChong.Web/ViewComponents/RightViewComponent.cs
using HuoChong.Data.IRepository;
using HuoChong.Entity.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HuoChong.WebManage.ViewComponents
{
    public class RightViewComponent: ViewComponent
    {
        public readonly INewsRepository _newsRepository;
        public readonly IColumnRepository _columnRepository;
        public RightViewComponent(INewsRepository newsRepository, IColumnRepository columnRepository)
        {
            _newsRepository = newsRepository;
            _columnRepository = columnRepository;
        }
        public async Task<IViewComponentResult> InvokeAsync(string ColumnParentSpell)
        {
            RightVM model = new RightVM() {
                ByMonthBrowseNews=( await _newsRepository.GetByBrowseNewsAsync("month")).ToList(),
                ByMonthLikeNews=(await _newsRepository.GetByLikeNewsAsync("month")).ToList(),
                AllChildColumnByParent= _columnRepository.GetChildcolumnByParentColumn(ColumnParentSpell),
                RamdomLikeList=_newsRepository.RandomNews()
            };          
            return View(model);
        }
    }
}

HuoChong.Web/Views/Home/About.cshtml
@{
    Layout = "~/Views/Shared/_GlobalLayout.cshtml";
    ViewData["Title"] = "火虫网_关于我们";
}

    <div class="whitebg about">
        <div class="ab_box">
            <i class="avatar_pic"><a href="/about/" target="_blank"><img src="/image/default.gif"></a></i>
            <h3>realyrare</h3>
            <p>一个90后.net程序员！熟悉javascript、css,html、.net core、sel server等领域。</p>


        </div>
        <h2 class="gd_title">关于火虫</h2><br />
        <p class="ab_dubai"></p>
        
        <p style="text-indent:2em;">
            <strong><a href="http://www.52huochong.com/">火虫网</a></strong>
            是一个面向大众的IT资源信息平台。自创建以来,以优质IT资源信息为理念,每天通过短视频,图文并茂形式分享后端开发、web前端、数据库、IT资讯等有价值、有生产力的信息。
        </p>
        <p style="text-indent:2em;">
            未来的时代人人都懂点编程，我们要做的是在学习编程知识的同时，要精益求精，所有的努力都是为了明天的生活更阳光，更美好，在如今人工智能，大数据满天飞的时代我们看到一些技术员常常忙于工作，在公作中更多的是增删改查的重复工作，导致自己的技术相比行业的其他人来说水准有待提高。所以火虫网在成立的时候就致力于优秀编程博客栖息地，更多关于疑难问题解决方案的提供者。另外一个愿景是一部分人不懂编程，也提供了一些<a href="http://www.52huochong.com/cate/biancheng/" target="_blank">后端开发</a>知识的优质文章供大家学习，做到这个时代爱生活、懂编程。
        </p>
        <p style="text-indent:2em;">最后如果大家在阅读本站文章时遇到困惑或其他问题，欢迎大家致信于我邮箱(mhg215@yeah.net)</p>

        @*<h2 class="gd_title">我的博客</h2>
        <ul class="myblog">
            <li>
                <b>创建时间</b>
                <p>2011年01月12日</p>
                <p><a href="http://www.yangqq.com" target="_blank" class="buttons">主页</a></p>
            </li>
            <li>
                <b>主题模板</b>
                <p><a href="http://www.yangqq.com" target="_blank">《今夕何夕》</a></p>
                <p><a href="http://www.yangqq.com/download/div/917.html" class="buttons">下载</a></p>
            </li>
            <li>
                <b>网站程序</b>
                <p>帝国CMS7.5</p>
                <p><a href="https://www.yangqq.com/blogs/876.html" target="_blank" class="buttons">为什么选帝国cms</a></p>
            </li>
            <li>
                <b>服务器商</b>
                <p>阿里云服务器</p>
                <a href="https://promotion.aliyun.com/ntms/yunparter/invite.html?userCode=l1qstn8f" class="buttons">1888代金券领取</a>
            </li>
            <li>
                <b>免费空间</b>
                <p><a href="http://www.4562.com/?u=3CE3E8" target="_blank">金牛云服</a></p>
                <a href="http://www.4562.com/?u=3CE3E8" class="buttons">国内主机免费领</a>
            </li>
        </ul>*@
        @*<h2 class="gd_title">加入我们</h2>
        <ul class="qq_join">
            <li>
                <section>
                    <img src="https://www.yangqq.com/skin/jxhx/image/qq1.png">
                    <p>网页设计交流吧①</p>
                    <p>QQ群号：280998807</p>
                </section>
            </li>
        </ul>*@
    </div>

HuoChong.Web/Views/Home/BarCode.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>
        特种作业人员信息
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="shortcut icon" href="~/top.ico" type="image/x-icon">
</head>
<body>
    <div id="IsOrEnble" style="max-width:1000px;margin:0 auto;text-align:center;">
        <div style="border:1px solid #4D4D4D">
            <img id="Image1" src="~/image/201904060903060.jpg" style="width:100%;">
            <div style="text-align:center;text-decoration:none;color:#666;margin-top:20px;">
                <table width="100%" align="center" cellpadding="0" cellspacing="0" border-color="#666" class="zstab" id="show" style="font-size:25px"></table>
            </div>
        </div>
    </div>
    <script>
        window.onload = function () {
            var show = document.getElementById("show");
            setInterval(function () {
                var time = new Date();
                // 程序计时的月从0开始取值后+1
                var m = time.getMonth() + 1;
                var t = time.getFullYear() + "年" + m + "月"
                  + time.getDate() + "日" + time.getHours() + ":"
                  + time.getMinutes() + ":" + time.getSeconds();
                show.innerHTML = '当前时间:' + t;
            }, 1000);
        };


    </script>
</body>
</html>

HuoChong.Web/Views/Home/Detail.cshtml
@{
    Layout = "~/Views/Shared/_GlobalLayout.cshtml";
    ViewData["Title"] = Model.Title+"-火虫网";
    ViewData["keywords"] = Model.KeyWord;
    ViewData["Description"] = Model.Intros;
    var newsColumnRealted = (List<NewsColumnRealtedVM>)ViewData["NewsColumnRelated"];
}
@using HuoChong.Tools
@using HuoChong.Entity
@using HuoChong.Entity.ViewModel
@model News
@section css{
    <link href="~/css/prettify.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/layer.css" rel="stylesheet" />
}
@section js{
    <script src="~/js/prettify.js"></script>
    <script src="~/js/run_prettify.js"></script>
    <script src="~/js/layer.js"></script>
}
<script>
    prettyPrint();
</script>

<div class="lbox">
    <div class="content_box whitebg">
        <h2 class="htitle"><span class="con_nav">您现在的位置是：<a href="/">首页</a>&nbsp;&gt;&nbsp;<a href="@domainConfig.CurrentValue.Host@Url.Action("newsList","home",new {columnParentSpell=Model.ColumnUrl})/">@Model.ColumnName</a></span>@Model.ColumnName</h2>
        <h1 class="con_tilte">@Model.Title</h1>
        <p class="bloginfo">
            <i class="avatar"><img src="/image/avatar.jpg"></i><span></span><span>@Model.CreateTime.ToString("yyyy-MM-dd")</span><span></span><span>
                @Html.Raw(Model.Views)人已围观
            </span>
        </p>
        <p class="con_info">
            <b>简介</b>@Model.Intros
        </p>
        <div class="con_text">
            @Html.Raw(WebHelper.DealwithContentImg(Model.Content))
            @*<p>Tags：<a href="" target="_blank">博客</a> &nbsp; <a href="" target="_blank">空间</a> &nbsp; <a href="" target="_blank">金牛云服</a></p>*@
            <p class="share"><b>转载：</b>感谢您对火虫网平台的认可，以及对我们原创作品以及文章的青睐，非常欢迎各位朋友分享到个人站长或者朋友圈，但转载请说明文章出处“火虫网”。</p>
            <p>
                <span class="diggit">
                    <a href="javascript:void(0)" id="btn-like"> 很赞哦!</a>
                    (<b id="diggnum">
                        @Model.Like
                    </b>)
                </span>
            </p>
            <div class="nextinfo">
                <p>
                    上一篇：
                    @if (ViewBag.UpId == null)
                    {
                        <a>暂无上篇信息</a>
                    }
                    else
                    {
                        <a href="@domainConfig.CurrentValue.Host@Url.Action("Detail","Home",new { id=ViewBag.UpId,columnUrl=Model.ColumnUrl})" title="@ViewBag.UpNews">@ViewBag.UpNews</a>
                    }
                </p>
                <p>
                    下一篇：
                    @if (ViewBag.NextId == null)
                    {
                        <a>暂无下篇信息</a>
                    }
                    else
                    {
                        <a href="@domainConfig.CurrentValue.Host@Url.Action("Detail","Home",new { id=ViewBag.NextId,columnUrl=Model.ColumnUrl})" title="@ViewBag.NextNews">@ViewBag.NextNews</a>
                    }
                </p>
            </div>
        </div>
    </div>
    <div class="whitebg">
        <h2 class="htitle">相关文章</h2>
        <ul class="otherlink">
            @if (newsColumnRealted.Count > 0)
            {
                foreach (var item in newsColumnRealted)
                {
                    <li><a href="@domainConfig.CurrentValue.Host@Url.Action("Detail", "Home", new { id = item.Id ,columnUrl=Model.ColumnUrl})" title="@item.Title">@item.Title</a></li>
                }
            }
            else
            {
                <li style="text-align:center">暂无相关内容</li>
            }
        </ul>
    </div>
    <div class="whitebg gbook">
        <h2 class="htitle">文章评论</h2>
        <ul>
            <div class="fb">

            </div>
            <form action="" method="post" name="saypl" id="saypl">
                <div id="plpost">
                    <p class="saying">
                        <span>
                            <a class="msg-count">
                               
                            </a>
                        </span>有话说,别藏着...
                    </p>
                    <p class="yname">
                        <span>邮箱:</span>
                        <input name="useremail" type="text" class="inputText" id="useremail" value="" size="16">
                    </p>
                    <input name="nomember" type="hidden" id="nomember" value="1" checked="checked">
                    <textarea name="saytext" rows="6" id="saytext"></textarea>
                    <input name="imageField" id="btnOk" type="button" value="提交">
                </div>
            </form>
        </ul>
    </div>
</div>
@await Component.InvokeAsync("Right", new { ColumnParentSpell = Model.ColumnUrl })
<script type="text/javascript">
    $(function ()
    {
        $("#btn-like").click(function () {
            $.post("/Home/ClickLikeNews", { newsId:'@Model.Id'}, function (data) {
                if (data == "ok") {
                    $("#diggnum").text(parseInt($("#diggnum").text()) + 1);
                }
            });
        });
        $("#btnOk").click(function () {
            var email = $("#useremail").val(), content = $("#saytext").val();
            var reg = /^([a-zA-Z]|[0-9])(\w|\-)+@@[a-zA-Z0-9]+\.([a-zA-Z]{2,4})$/;

            if (email == "") {
                layer.msg("邮箱不能为空");
                return;
            }
            if (!reg.test(email)) {
                layer.msg("请填写正确的邮箱");
                return;
            }
            if (content == "") {
                layer.msg("您会留言吗");
                return;
            }
            $.post("/Home/AddMessage", { newsId:'@Model.Id',content:content,email:email}, function (data) {
                if (data == "ok") {
                    $("#useremail").val('');
                    $("#saytext").val('');
                    loadMessage();
                } else {
                    layer.msg("留言失败了");
                    return;
                }
            });
        });
        loadMessage();
    });
    function loadMessage() {
        $.getJSON("/Home/LoadMessage", { newsId: '@Model.Id' }, function (data) {
            if (data != null) {
                var html = "";
                for (var i in data.data)
                    {
                    html +=('<ul><p class="fbtime"><span>' + data.data[i].CreateTime + '</span> ' + data.data[i].Email + '</p><p class="fbinfo">' + data.data[i].Content + '</p></ul>');
                }
                $(".fb").html(html);
                $(".msg-count").html("共有"+data.count+"条评论")
            }
        });
    }
</script>

HuoChong.Web/Views/Home/Link.cshtml
@{
    Layout = "~/Views/Shared/_GlobalLayout.cshtml";
    ViewData["Title"] = "火虫网-优秀博客网站推荐";
    ViewData["keywords"] = "火虫网,火虫网优秀个人博客推荐,个人站长,博客,个人博客,优秀的个人博客,个人网站,优秀的个人网站";
    ViewData["Description"] = "这是一个站长博客导航平台,火虫网实力推荐优秀优秀站点和个人博客,提供优秀的博客网站预览。每个网站和博客都有自己的一技之长,大家一起共勉。";
}
@using HuoChong.Entity;
<div class="whitebg">
    <h2 class="htitle"><span class="hnav">可能，你觉得自己没有足够得优秀，但我始终相信你仍然在努力坚持着!</span>站长推荐</h2>
    <ul class="site_tj">
        @foreach (var item in (List<SpliderSite>)ViewData["linkUrlList"])
        {
            <li>
                <a href="@item.Url" target="_blank" rel="nofollow">@item.Name</a>
            </li>
        }
    </ul>
</div>
<div class="whitebg">
    <h2 class="htitle">网盘资源搜索</h2>
    <ul class="site_tj site_yx">
        <li>
            <a href="https://xiaokesoso.com/" target="_blank" rel="nofollow">小可搜搜</a>
        </li>
        <li><a href="http://www.panduoduo.net/" target="_blank" rel="nofollow">盘多多</a></li>
    </ul>
</div>

HuoChong.Web/Views/Home/NewsList.cshtml
@{
    Layout = "~/Views/Shared/_GlobalLayout.cshtml";
    ViewData["Title"] = Model.Title + "-火虫网";
    ViewData["keywords"] = Model.Keywords;
    ViewData["Description"] = Model.Description;
    var newsList = (List<NewsPageVM>)ViewData["NewsList"];
}
@using X.PagedList.Mvc.Core;
@using X.PagedList;
@using HuoChong.Entity.ViewModel
@using HuoChong.Tools
@model NewsListVM
@section css{
    <link href="~/css/PagedList.min.css" rel="stylesheet" asp-append-version="true" />
}
<div class="lbox">
    <div class="whitebg lanmu">        
        <h1>@Model.CurrentColumnParentName</h1>
        <p>@Model.Description</p>
    </div>
    <div class="whitebg bloglist">
        <h2 class="htitle">最新文章</h2>
        <ul>
            @foreach (var item in newsList)
            {

                string imgSrc = WebHelper.GetContentFirstImg(item.Content);
                <li>
                    <h3 class="blogtitle"><b>【@item.Views】</b><a href="@domainConfig.CurrentValue.Host@Url.Action("Detail","Home",new{Id=item.Id,columnUrl=item.ColumnUrl})" target="_blank" title="@item.Title">@item.Title</a></h3>

                    @if (!string.IsNullOrEmpty(imgSrc))
                    {
                        <span class="blogpic imgscale">
                            <i>
                               
                            </i><a href="@domainConfig.CurrentValue.Host@Url.Action("Detail", "Home", new { Id = item.Id, columnUrl = item.ColumnUrl })" title="@item.Title">

                                <img src="/image/loading.gif" alt="@item.Title" data-echo="@domainConfig.CurrentValue.ImgHost@imgSrc" />
                            </a>
                        </span>
                    }
                    <p class="blogtext">@Html.Raw(item.Intros)</p>
                    <p class="bloginfo">
                        <i class="avatar">
                            <a href="@domainConfig.CurrentValue.Host@Url.Action("Detail","Home",new{Id=item.Id,columnUrl=item.ColumnUrl})" target="_blank" title="@item.Title">
                                <img src="/image/avatar.jpg" border="0" width="30" height="30" alt="@item.Title">
                            </a>
                        </i><span></span><span>@item.CreateTime.ToString("yyyy-MM-dd")</span><span>【<a href="@Url.Action("newslist","home",new { columnParentSpell=item.ColumnUrl})/" title="">@item.ColumnName</a>】</span>
                    </p>
                    <a href="@domainConfig.CurrentValue.Host@Url.Action("Detail","Home",new{Id=item.Id,columnUrl=item.ColumnUrl})" title="@item.Title" class="viewmore">阅读全文</a>
                </li>
            }
        </ul>
       
        <div class="pagelist">
            @Html.PagedListPager((IPagedList<NewsPageVM>)ViewData["Page"], page => Url.Action("NewsList", new { page, columnParentSpell = Model.CurrentColumnParentSpell }))
        </div>   
    </div>
    <!--bloglist end-->
</div>
@await Component.InvokeAsync("Right",new { ColumnParentSpell=Model.CurrentColumnParentSpell })

HuoChong.Web/Views/Home/Search.cshtml
@{
    Layout = "~/Views/Shared/_GlobalLayout.cshtml";
}
@using HuoChong.Tools
@using HuoChong.Entity.ViewModel
@using HuoChong.Entity
@using X.PagedList.Mvc.Core;
@using X.PagedList;
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Search</title>
    @section css{
        <link href="~/css/PagedList.min.css" rel="stylesheet" asp-append-version="true" />
    }
</head>

<body>
    <div class="zhuanti whitebg">
        <h2 class="htitle" style="color:red;font-weight:500"><span class="hnav"></span>@TempData["CurrentKeyword"]</h2>
        <ul>
            @foreach (var item in (List<NewsPageVM>)ViewData["NewsSearchList"])
            {
                string imgSrc = WebHelper.GetContentFirstImg(item.Content);
                <li>
                    <i class="ztpic">
                        <a href="@domainConfig.CurrentValue.Host@Url.Action("Detail","Home",new{Id=item.Id,columnUrl=item.ColumnUrl})" target="_blank" title="@item.Title">
                            @if (!string.IsNullOrEmpty(imgSrc))
                            {
                                <img src="@domainConfig.CurrentValue.ImgHost@imgSrc" alt="@item.Title" />
                            }
                            else
                            {
                                <img src="/image/banner_1.jpg" alt="@item.Title" />
                            }
                        </a>
                    </i> <b>@item.Title</b>
                    <span>
                        @Html.Raw(item.Intros)
                    </span>
                    <a href="@domainConfig.CurrentValue.Host@Url.Action("Detail","Home",new{Id=item.Id,columnUrl=item.ColumnUrl})" target="_blank" title="@item.Title" class="readmore">阅读原文</a>
                </li>
            }
        </ul>
        
    </div>
    <div class="pagelist">
        @Html.PagedListPager((IPagedList<NewsPageVM>)ViewData["Page"], page => Url.Action("Search", new { page, keyword= TempData["CurrentKeyword"] }))
    </div>
</body>
</html>